[egui]
right = "h"
left = "l"
up = "k"
down = "j"
next = "n"
previous = "N"
next_window = "<cr> + n"
previous_window = "<cr> + N"

[winit]
help = "<cr> + H"
menu = "<cr> + M"
decorations = "<alt> + d"
fullscreen = "<alt> + f"
maximize = "<alt> + s"
minimize = "<alt> + S"
